---
name: CI

on: [push]

jobs:
  build-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - os: windows-latest
            generator: VS16Win64
          - os: ubuntu-20.04
            generator: Ninja
          - os: macos-latest
            generator: Ninja
    steps:
      - name: Download Source
        uses: actions/checkout@v2

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Run CMake
        uses: lukka/run-cmake@v3
        with:
          cmakeGenerator: ${{ matrix.generator }}
          cmakeBuildType: Release
          buildDirectory: ${{ github.workspace }}/build

      - name: Run Tests
        run: |
          cd build
          ctest
...
